layout_spectrum: 0.1070201
color:
  saturation: 0.7812726
  lightness: 0.9766621
  brandStrength: 0.7769673
  rhythmicContrast: 0.8094091
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.2656642
name: Survivor Media
