name: Survivor Media
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2656642
title: Survivor Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#19a68d'
    - '#e26343'
    - '#63705d'
    - '#efa793'
  brandStrength: 0.5
  lightness: 0.9766621
  saturation: 0.7812726
  rhythmicContrast: 0.8094091
purpose: []
